#!/bin/bash
# Script para revocar API keys expuestas
# EJECUTAR INMEDIATAMENTE si las keys están comprometidas

echo "🚨 REVOCACIÓN DE API KEYS EXPUESTAS"
echo "===================================="
echo ""
echo "Este script te guiará para revocar las API keys que pueden estar comprometidas."
echo ""
echo "ACCIONES REQUERIDAS:"
echo ""
echo "1. OpenAI API Key:"
echo "   - Ir a: https://platform.openai.com/api-keys"
echo "   - Revocar la key expuesta"
echo "   - Generar nueva key"
echo "   - Actualizar .env con nueva key"
echo ""
echo "2. Cartesia API Key:"
echo "   - Ir a: https://console.cartesia.ai/settings/api-keys"
echo "   - Revocar la key expuesta"
echo "   - Generar nueva key"
echo ""
echo "3. Deepgram API Key:"
echo "   - Ir a: https://console.deepgram.com/project/keys"
echo "   - Revocar la key expuesta"
echo "   - Generar nueva key"
echo ""
echo "4. HeyGen API Key (si aplica):"
echo "   - Revocar en el dashboard de HeyGen"
echo "   - Generar nueva key"
echo ""
echo "⚠️  IMPORTANTE:"
echo "   - NO usar las keys expuestas nunca más"
echo "   - Actualizar .env inmediatamente"
echo "   - Verificar que .env esté en .gitignore"
echo "   - No commitear archivos con keys"
echo ""
echo "✅ Después de revocar, ejecutar:"
echo "   npm run security-check"
echo ""

